# Generated by Django 6.0.6 on 2026-06-23 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=2000, verbose_name='Nome da demanda')),
                ('tipo', models.CharField(choices=[('evolutiva', 'Evolutiva'), ('corretiva', 'Corretiva'), ('indicacao_rubrica', 'Indicação de Rubrica'), ('criacao_objeto', 'Criação de Objeto')], db_index=True, max_length=30, verbose_name='Tipo')),
                ('classificacao', models.CharField(blank=True, default='', max_length=200, verbose_name='Classificação')),
                ('status', models.CharField(choices=[('nao_iniciada', 'Não Iniciada'), ('em_andamento', 'Em Andamento'), ('concluida', 'Concluída')], db_index=True, default='nao_iniciada', max_length=20, verbose_name='Status')),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='Data de início')),
                ('data_conclusao', models.DateField(blank=True, null=True, verbose_name='Data de conclusão')),
                ('processo_sei', models.CharField(blank=True, default='', max_length=300, verbose_name='Processo SEI')),
                ('processo_relacionado', models.TextField(blank=True, default='', verbose_name='Processo relacionado')),
                ('alm', models.CharField(blank=True, default='', max_length=100, verbose_name='ALM')),
                ('localizacao', models.CharField(blank=True, default='', max_length=500, verbose_name='Localização')),
                ('reiterada', models.BooleanField(default=False, verbose_name='Demanda reiterada')),
                ('data_reiteracao', models.DateField(blank=True, null=True, verbose_name='Data de reiteração')),
                ('priorizacao', models.IntegerField(blank=True, null=True, verbose_name='Priorização')),
                ('observacoes', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Demanda',
                'verbose_name_plural': 'Demandas',
                'ordering': ['tipo', 'priorizacao', '-criado_em'],
                'indexes': [models.Index(fields=['tipo', 'status'], name='monitoramen_tipo_7fb3c8_idx'), models.Index(fields=['data_inicio'], name='monitoramen_data_in_4f57cd_idx')],
            },
        ),
    ]
