# Generated by Django 6.0.6 on 2026-07-02 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0004_datas_assinatura_sei'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjetoGestao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_objeto', models.CharField(blank=True, db_index=True, default='', max_length=80, verbose_name='ID do objeto')),
                ('nome', models.CharField(db_index=True, max_length=2000, verbose_name='Nome do objeto')),
                ('descricao', models.TextField(blank=True, default='', verbose_name='Descricao')),
                ('grupo', models.CharField(blank=True, db_index=True, default='', max_length=300, verbose_name='Grupo de objetos')),
                ('ativo', models.BooleanField(blank=True, db_index=True, null=True, verbose_name='Ativo')),
                ('data_encerramento', models.DateField(blank=True, null=True, verbose_name='Data de encerramento')),
                ('processo_sei', models.CharField(blank=True, default='', max_length=300, verbose_name='Processo SEI')),
                ('ajs_ativas', models.TextField(blank=True, default='', verbose_name='AJs ativas')),
                ('tipo_objeto', models.CharField(blank=True, default='', max_length=300, verbose_name='Tipo de objeto')),
                ('carater', models.CharField(blank=True, db_index=True, default='', max_length=200, verbose_name='Carater')),
                ('fluxo_confirmacao', models.CharField(blank=True, db_index=True, default='', max_length=300, verbose_name='Fluxo de confirmacao')),
                ('passivel_absorcao', models.BooleanField(blank=True, null=True, verbose_name='Passivel de absorcao')),
                ('tema', models.CharField(blank=True, db_index=True, default='', max_length=500, verbose_name='Tema')),
                ('subtema', models.CharField(blank=True, default='', max_length=500, verbose_name='Subtema')),
                ('pedido_inicial', models.TextField(blank=True, default='', verbose_name='Pedido inicial')),
                ('limite_maximo_objeto', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Limite maximo do objeto')),
                ('observacao', models.TextField(blank=True, default='', verbose_name='Observacao')),
                ('aba_origem', models.CharField(blank=True, default='', max_length=200, verbose_name='Aba de origem')),
                ('linha_origem', models.PositiveIntegerField(blank=True, null=True, verbose_name='Linha de origem')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('demanda_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objetos_gestao_migrados', to='monitoramento.demanda', verbose_name='Demanda de origem')),
            ],
            options={
                'verbose_name': 'Objeto de Gestao',
                'verbose_name_plural': 'Objetos de Gestao',
                'ordering': ['grupo', 'nome'],
                'indexes': [models.Index(fields=['grupo', 'ativo'], name='monitoramen_grupo_4cbdde_idx'), models.Index(fields=['carater', 'fluxo_confirmacao'], name='monitoramen_carater_c450a7_idx'), models.Index(fields=['tema'], name='monitoramen_tema_a9c8f9_idx')],
            },
        ),
    ]
