# Generated by Django 6.0.6 on 2026-07-02 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0006_migrar_gestao_objetos'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='documentosei',
            new_name='monitoramen_process_fd2912_idx',
            old_name='monitoramen_processo_e2004d_idx',
        ),
        migrations.RenameIndex(
            model_name='documentosei',
            new_name='monitoramen_tipo_9f5548_idx',
            old_name='monitoramen_tipo_599dfb_idx',
        ),
        migrations.RenameIndex(
            model_name='processosei',
            new_name='monitoramen_numero__a156dd_idx',
            old_name='monitoramen_numero__4dcf0d_idx',
        ),
        migrations.RenameIndex(
            model_name='processosei',
            new_name='monitoramen_assunto_865913_idx',
            old_name='monitoramen_assunto_102f99_idx',
        ),
    ]
